### ISSUE TITLE
android.content.ActivityNotFoundException: Unable to find explicit activity class {io.github.TomGarden.tetris/io.github.TomGarden.GenerateRevenue.GoogleAdMod}; have you declared this activity in your AndroidManifest.xml?

### ISSUE THREAD

**Issue by TomGarden-2** [TomGarden/Tetris#16]
```
/*Device Info*/
[硬]设备制造商=Genymotion
[硬]设备型号=Custom
[硬]CPU型号=null
[硬]RAM=1.04 GB
[硬]ROM=13.38 GB
[OS][三方定制系统版本]=Android/vbox86p/vbox86p:8.0.0/OPR6.170623.017/32:userdebug/test-keys
[OS]产品名称(adb shell)=vbox86p
[OS][系统名称]=Android
[OS][Android版本]=8.0.0(26)
[app]versionName=1.0
[app]versionCode=1
/*Exception*/
android.content.ActivityNotFoundException: Unable to find explicit activity class {io.github.TomGarden.tetris/io.github.TomGarden.GenerateRevenue.GoogleAdMod}; have you declared this activity in your AndroidManifest.xml?
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1932)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1747)
	at android.app.Activity.startActivityForResult(Activity.java:5153)
	at android.app.Activity.startActivityFromFragment(Activity.java:5129)
	at android.app.Activity$HostCallbacks.onStartActivityFromFragment(Activity.java:7602)
	at android.app.Fragment.startActivity(Fragment.java:1179)
	at android.app.Fragment.startActivity(Fragment.java:1158)
	at io.github.TomGarden.tetris.Fragments.SettingPreferenceFragment.onPreferenceClick(SettingPreferenceFragment.java:66)
	at android.preference.Preference.performClick(Preference.java:1136)
	at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:249)
	at android.widget.AdapterView.performItemClick(AdapterView.java:318)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1165)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3134)
	at android.widget.AbsListView$3.run(AbsListView.java:4049)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

```

**Comment by TomGarden-2** [comment]
```
/*Device Info*/
[硬]设备制造商=Genymotion
[硬]设备型号=Custom
[硬]CPU型号=null
[硬]RAM=1.04 GB
[硬]ROM=13.38 GB
[OS][三方定制系统版本]=Android/vbox86p/vbox86p:8.0.0/OPR6.170623.017/32:userdebug/test-keys
[OS]产品名称(adb shell)=vbox86p
[OS][系统名称]=Android
[OS][Android版本]=8.0.0(26)
[app]versionName=1.0
[app]versionCode=1
/*Exception*/
android.content.ActivityNotFoundException: Unable to find explicit activity class {io.github.TomGarden.tetris/io.github.TomGarden.GenerateRevenue.GoogleAdMod}; have you declared this activity in your AndroidManifest.xml?
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1932)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1747)
	at android.app.Activity.startActivityForResult(Activity.java:5153)
	at android.app.Activity.startActivityFromFragment(Activity.java:5129)
	at android.app.Activity$HostCallbacks.onStartActivityFromFragment(Activity.java:7602)
	at android.app.Fragment.startActivity(Fragment.java:1179)
	at android.app.Fragment.startActivity(Fragment.java:1158)
	at io.github.TomGarden.tetris.Fragments.SettingPreferenceFragment.onPreferenceClick(SettingPreferenceFragment.java:66)
	at android.preference.Preference.performClick(Preference.java:1136)
	at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:249)
	at android.widget.AdapterView.performItemClick(AdapterView.java:318)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1165)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3134)
	at android.widget.AbsListView.onTouchUp(AbsListView.java:4061)
	at android.widget.AbsListView.onTouchEvent(AbsListView.java:3820)
	at android.view.View.dispatchTouchEvent(View.java:11721)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2955)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2636)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2961)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2961)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2961)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2961)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2961)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2961)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2961)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2961)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2961)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:445)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1828)
	at android.app.Activity.dispatchTouchEvent(Activity.java:3292)
	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:407)
	at android.view.View.dispatchPointerEvent(View.java:11960)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4776)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4590)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4128)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4181)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4147)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4274)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4155)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4331)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4128)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4181)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4147)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4155)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4128)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6642)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6616)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6577)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6745)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:325)
	at android.os.Looper.loop(Looper.java:142)
	at android.app.ActivityThread.main(ActivityThread.java:6541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

```
