### ISSUE TITLE
android.content.ActivityNotFoundException: Unable to find explicit activity class {io.github.TomGarden.tetris_25/io.github.TomGarden.tetris_25.Activities.CustomThemeActivity}; have you declared this activity in your AndroidManifest.xml?

### ISSUE THREAD

**Issue by TomGarden-2** [TomGarden/Tetris#17]
```
/*Device Info*/
[硬]设备制造商=Genymotion
[硬]设备型号=Custom
[硬]CPU型号=null
[硬]RAM=1.04 GB
[硬]ROM=13.38 GB
[OS][三方定制系统版本]=Android/vbox86p/vbox86p:8.0.0/OPR6.170623.017/32:userdebug/test-keys
[OS]产品名称(adb shell)=vbox86p
[OS][系统名称]=Android
[OS][Android版本]=8.0.0(26)
[app]versionName=1.0
[app]versionCode=1
/*Exception*/
android.content.ActivityNotFoundException: Unable to find explicit activity class {io.github.TomGarden.tetris_25/io.github.TomGarden.tetris_25.Activities.CustomThemeActivity}; have you declared this activity in your AndroidManifest.xml?
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1932)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1615)
	at android.app.Activity.startActivityForResult(Activity.java:4472)
	at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:767)
	at android.app.Activity.startActivityForResult(Activity.java:4430)
	at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:754)
	at android.app.Activity.startActivity(Activity.java:4791)
	at android.app.Activity.startActivity(Activity.java:4759)
	at android.preference.Preference.performClick(Preference.java:1152)
	at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:249)
	at android.widget.AdapterView.performItemClick(AdapterView.java:318)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1165)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3134)
	at android.widget.AbsListView$3.run(AbsListView.java:4049)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

```

**Comment by TomGarden-2** [comment]
```
/*Device Info*/
[硬]设备制造商=Genymotion
[硬]设备型号=Custom
[硬]CPU型号=null
[硬]RAM=1.04 GB
[硬]ROM=13.38 GB
[OS][三方定制系统版本]=Android/vbox86p/vbox86p:8.0.0/OPR6.170623.017/32:userdebug/test-keys
[OS]产品名称(adb shell)=vbox86p
[OS][系统名称]=Android
[OS][Android版本]=8.0.0(26)
[app]versionName=1.0
[app]versionCode=1
/*Exception*/
android.content.ActivityNotFoundException: Unable to find explicit activity class {io.github.TomGarden.tetris_25/io.github.TomGarden.tetris_25.Activities.CustomThemeActivity}; have you declared this activity in your AndroidManifest.xml?
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1932)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1615)
	at android.app.Activity.startActivityForResult(Activity.java:4472)
	at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:767)
	at android.app.Activity.startActivityForResult(Activity.java:4430)
	at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:754)
	at android.app.Activity.startActivity(Activity.java:4791)
	at android.app.Activity.startActivity(Activity.java:4759)
	at android.preference.Preference.performClick(Preference.java:1152)
	at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:249)
	at android.widget.AdapterView.performItemClick(AdapterView.java:318)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1165)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3134)
	at android.widget.AbsListView$3.run(AbsListView.java:4049)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

```
