### ISSUE TITLE
java.lang.RuntimeException: Failure delivering result ResultInfo{who=android:fragment:2, request=6709, result=-1, data=Intent { (has extras) }} to activity {io.github.TomGarden.tetris/io.github.TomGarden.tetris.Activities.CustomGameStyleActivity}: java.lan

### ISSUE THREAD

**Issue by TomGarden-2** [TomGarden/Tetris#26]
```
/*Device Info*/
[硬]设备制造商=Genymotion
[硬]设备型号=Custom
[硬]CPU型号=null
[硬]RAM=1.04 GB
[硬]ROM=13.38 GB
[OS][三方定制系统版本]=Android/vbox86p/vbox86p:8.0.0/OPR6.170623.017/32:userdebug/test-keys
[OS]产品名称(adb shell)=vbox86p
[OS][系统名称]=Android
[OS][Android版本]=8.0.0(26)
[app]versionName=1.0
[app]versionCode=1
/*Exception*/
java.lang.RuntimeException: Failure delivering result ResultInfo{who=android:fragment:2, request=6709, result=-1, data=Intent { (has extras) }} to activity {io.github.TomGarden.tetris/io.github.TomGarden.tetris.Activities.CustomGameStyleActivity}: java.lang.RuntimeException: (SettingGameStylePreferenceFragment.java:771)>>>Logic ERR
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4324)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4367)
	at android.app.ActivityThread.-wrap19(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1649)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
Caused by: java.lang.RuntimeException: (SettingGameStylePreferenceFragment.java:771)>>>Logic ERR
	at io.github.TomGarden.tom_log.LogUtil.ASSERT(LogUtil.java:252)
	at io.github.TomGarden.tetris.Fragments.SettingGameStylePreferenceFragment.onActivityResult(SettingGameStylePreferenceFragment.java:771)
	at android.app.Activity.dispatchActivityResult(Activity.java:7262)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4320)
	... 9 more
java.lang.RuntimeException: (SettingGameStylePreferenceFragment.java:771)>>>Logic ERR
	at io.github.TomGarden.tom_log.LogUtil.ASSERT(LogUtil.java:252)
	at io.github.TomGarden.tetris.Fragments.SettingGameStylePreferenceFragment.onActivityResult(SettingGameStylePreferenceFragment.java:771)
	at android.app.Activity.dispatchActivityResult(Activity.java:7262)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4320)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4367)
	at android.app.ActivityThread.-wrap19(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1649)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

```

**Comment by TomGarden-2** [comment]
```
/*Device Info*/
[硬]设备制造商=Genymotion
[硬]设备型号=Custom
[硬]CPU型号=null
[硬]RAM=1.04 GB
[硬]ROM=13.38 GB
[OS][三方定制系统版本]=Android/vbox86p/vbox86p:8.0.0/OPR6.170623.017/32:userdebug/test-keys
[OS]产品名称(adb shell)=vbox86p
[OS][系统名称]=Android
[OS][Android版本]=8.0.0(26)
[app]versionName=1.0
[app]versionCode=1
/*Exception*/
java.lang.RuntimeException: Failure delivering result ResultInfo{who=android:fragment:2, request=6709, result=-1, data=Intent { (has extras) }} to activity {io.github.TomGarden.tetris/io.github.TomGarden.tetris.Activities.CustomGameStyleActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4324)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4367)
	at android.app.ActivityThread.-wrap19(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1649)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
	at io.github.TomGarden.tetris.Fragments.SettingGameStylePreferenceFragment.onActivityResult(SettingGameStylePreferenceFragment.java:777)
	at android.app.Activity.dispatchActivityResult(Activity.java:7262)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4320)
	... 9 more
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
	at io.github.TomGarden.tetris.Fragments.SettingGameStylePreferenceFragment.onActivityResult(SettingGameStylePreferenceFragment.java:777)
	at android.app.Activity.dispatchActivityResult(Activity.java:7262)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4320)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4367)
	at android.app.ActivityThread.-wrap19(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1649)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

```

**Comment by TomGarden-2** [comment]
```
/*Device Info*/
[硬]设备制造商=Genymotion
[硬]设备型号=Custom
[硬]CPU型号=null
[硬]RAM=1.04 GB
[硬]ROM=13.38 GB
[OS][三方定制系统版本]=Android/vbox86p/vbox86p:8.0.0/OPR6.170623.017/32:userdebug/test-keys
[OS]产品名称(adb shell)=vbox86p
[OS][系统名称]=Android
[OS][Android版本]=8.0.0(26)
[app]versionName=1.0
[app]versionCode=1
/*Exception*/
java.lang.RuntimeException: Failure delivering result ResultInfo{who=android:fragment:2, request=6709, result=-1, data=Intent { (has extras) }} to activity {io.github.TomGarden.tetris/io.github.TomGarden.tetris.Activities.CustomGameStyleActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4324)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4367)
	at android.app.ActivityThread.-wrap19(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1649)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
	at io.github.TomGarden.tetris.Fragments.SettingGameStylePreferenceFragment.onActivityResult(SettingGameStylePreferenceFragment.java:777)
	at android.app.Activity.dispatchActivityResult(Activity.java:7262)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4320)
	... 9 more
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
	at io.github.TomGarden.tetris.Fragments.SettingGameStylePreferenceFragment.onActivityResult(SettingGameStylePreferenceFragment.java:777)
	at android.app.Activity.dispatchActivityResult(Activity.java:7262)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4320)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4367)
	at android.app.ActivityThread.-wrap19(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1649)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

```
