### ISSUE TITLE
java.lang.RuntimeException: Unable to pause activity {io.github.TomGarden.tetris/io.github.TomGarden.tetris.Activities.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'io.github.TomGarden.tetris.Control.GameState io.github.T

### ISSUE THREAD

**Issue by TomGarden-2** [TomGarden/Tetris#39]
```
/*Device Info*/
[硬]设备制造商=Genymotion
[硬]设备型号=Custom
[硬]CPU型号=null
[硬]RAM=1.04 GB
[硬]ROM=13.38 GB
[OS][三方定制系统版本]=Android/vbox86p/vbox86p:8.0.0/OPR6.170623.017/32:userdebug/test-keys
[OS]产品名称(adb shell)=vbox86p
[OS][系统名称]=Android
[OS][Android版本]=8.0.0(26)
[app]versionName=1.0
[app]versionCode=1
/*Exception*/
java.lang.RuntimeException: Unable to pause activity {io.github.TomGarden.tetris/io.github.TomGarden.tetris.Activities.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'io.github.TomGarden.tetris.Control.GameState io.github.TomGarden.tetris.Control.TomHandler.getGameState()' on a null object reference
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:3976)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3942)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3916)
	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3890)
	at android.app.ActivityThread.-wrap15(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1605)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'io.github.TomGarden.tetris.Control.GameState io.github.TomGarden.tetris.Control.TomHandler.getGameState()' on a null object reference
	at io.github.TomGarden.tetris.Activities.MainActivity.onPause(MainActivity.java:220)
	at android.app.Activity.performPause(Activity.java:7115)
	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1407)
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:3965)
	... 11 more
java.lang.NullPointerException: Attempt to invoke virtual method 'io.github.TomGarden.tetris.Control.GameState io.github.TomGarden.tetris.Control.TomHandler.getGameState()' on a null object reference
	at io.github.TomGarden.tetris.Activities.MainActivity.onPause(MainActivity.java:220)
	at android.app.Activity.performPause(Activity.java:7115)
	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1407)
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:3965)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3942)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3916)
	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3890)
	at android.app.ActivityThread.-wrap15(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1605)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

```

**Comment by TomGarden-2** [comment]
```
/*Device Info*/
[硬]设备制造商=unknown
[硬]设备型号=9.0
[硬]CPU型号=null
[硬]RAM=1.02 GB
[硬]ROM=13.44 GB
[OS][三方定制系统版本]=Android/vbox86p/vbox86p:9/PD1A.180720.031/51:userdebug/test-keys
[OS]产品名称(adb shell)=vbox86p
[OS][系统名称]=Android
[OS][Android版本]=9(28)
[app]versionName=0.2.5-internal.2
[app]versionCode=5
/*Exception*/
java.lang.RuntimeException: Unable to pause activity {io.github.TomGarden.tetris/io.github.TomGarden.tetris.Activities.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'io.github.TomGarden.tetris.Control.GameState io.github.TomGarden.tetris.Control.TomHandler.getGameState()' on a null object reference
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4032)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3987)
	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3939)
	at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1809)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6680)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'io.github.TomGarden.tetris.Control.GameState io.github.TomGarden.tetris.Control.TomHandler.getGameState()' on a null object reference
	at io.github.TomGarden.tetris.Activities.MainActivity.onPause(MainActivity.java:219)
	at android.app.Activity.performPause(Activity.java:7329)
	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1465)
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4022)
	... 12 more
java.lang.NullPointerException: Attempt to invoke virtual method 'io.github.TomGarden.tetris.Control.GameState io.github.TomGarden.tetris.Control.TomHandler.getGameState()' on a null object reference
	at io.github.TomGarden.tetris.Activities.MainActivity.onPause(MainActivity.java:219)
	at android.app.Activity.performPause(Activity.java:7329)
	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1465)
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4022)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3987)
	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3939)
	at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1809)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6680)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

```
