### ISSUE TITLE
java.lang.ClassCastException: android.support.constraint.ConstraintLayout cannot be cast to android.widget.LinearLayout

### ISSUE THREAD

**Issue by TomGarden-2** [TomGarden/Tetris#42]
```
/*Device Info*/
[硬]设备制造商=unknown
[硬]设备型号=API 21 - 5.0.0 - 480 x 854 - 240dpi
[硬]CPU型号=null
[硬]RAM=0.97 GB
[硬]ROM=4.84 GB
[OS][三方定制系统版本]=generic/vbox86p/vbox86p:5.0/LRX21M/17:userdebug/test-keys
[OS]产品名称(adb shell)=vbox86p
[OS][系统名称]=generic
[OS][Android版本]=5.0(21)
[app]versionName=1.0
[app]versionCode=1
/*Exception*/
java.lang.ClassCastException: android.support.constraint.ConstraintLayout cannot be cast to android.widget.LinearLayout
	at io.github.TomGarden.tetris.Fragments.IssuesFragment.onCreateView(IssuesFragment.java:27)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java:2346)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1428)
	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
	at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
	at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
	at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
	at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2215)
	at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:649)
	at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:145)
	at android.support.v4.view.ViewPager.populate(ViewPager.java:1238)
	at android.support.v4.view.ViewPager.populate(ViewPager.java:1086)
	at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1616)
	at android.view.View.measure(View.java:17430)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5463)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
	at android.view.View.measure(View.java:17430)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5463)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
	at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:141)
	at android.view.View.measure(View.java:17430)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5463)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
	at android.view.View.measure(View.java:17430)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5463)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
	at android.view.View.measure(View.java:17430)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5463)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
	at android.view.View.measure(View.java:17430)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5463)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2560)
	at android.view.View.measure(View.java:17430)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2001)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1166)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1372)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1054)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5779)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
	at android.view.Choreographer.doCallbacks(Choreographer.java:580)
	at android.view.Choreographer.doFrame(Choreographer.java:550)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5221)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

```

**Comment by TomGarden-2** [comment]
```
/*Device Info*/
[硬]设备制造商=unknown
[硬]设备型号=API 21 - 5.0.0 - 480 x 854 - 240dpi
[硬]CPU型号=null
[硬]RAM=0.97 GB
[硬]ROM=4.84 GB
[OS][三方定制系统版本]=generic/vbox86p/vbox86p:5.0/LRX21M/17:userdebug/test-keys
[OS]产品名称(adb shell)=vbox86p
[OS][系统名称]=generic
[OS][Android版本]=5.0(21)
[app]versionName=1.0
[app]versionCode=1
/*Exception*/
java.lang.ClassCastException: android.support.constraint.ConstraintLayout cannot be cast to android.widget.LinearLayout
	at io.github.TomGarden.tetris.Fragments.IssuesFragment.onCreateView(IssuesFragment.java:27)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java:2346)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1428)
	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
	at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
	at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
	at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
	at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2215)
	at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:649)
	at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:145)
	at android.support.v4.view.ViewPager.populate(ViewPager.java:1238)
	at android.support.v4.view.ViewPager.populate(ViewPager.java:1086)
	at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1616)
	at android.view.View.measure(View.java:17430)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5463)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
	at android.view.View.measure(View.java:17430)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5463)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
	at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:141)
	at android.view.View.measure(View.java:17430)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5463)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
	at android.view.View.measure(View.java:17430)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5463)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
	at android.view.View.measure(View.java:17430)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5463)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
	at android.view.View.measure(View.java:17430)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5463)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2560)
	at android.view.View.measure(View.java:17430)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2001)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1166)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1372)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1054)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5779)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
	at android.view.Choreographer.doCallbacks(Choreographer.java:580)
	at android.view.Choreographer.doFrame(Choreographer.java:550)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5221)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

```
