### ISSUE TITLE
java.lang.RuntimeException: 测试 

### ISSUE THREAD

**Issue by TomGarden-2** [TomGarden/Tetris#5]
java.lang.RuntimeException: 测试 
	at com.farbox.androidbyeleven.View.Activity.MainActivity.test(MainActivity.java:293)
	at com.farbox.androidbyeleven.View.Activity.MainActivity.onClick(MainActivity.java:286)
	at android.view.View.performClick(View.java:4756)
	at android.view.View$PerformClick.run(View.java:19749)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5221)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by TomGarden-2** [comment]
```
/*Device Info*/
「OS」「系统名称」=generic
「OS」产品名称(adb shell)=vbox86p
「硬」CPU型号=null
「硬」设备制造商=unknown
「app」versionName=1.0
「OS」「Android版本」=5.0(21)
「app」versionCode=1
「OS」「三方定制系统版本」=generic/vbox86p/vbox86p:5.0/LRX21M/17:userdebug/test-keys
「硬」ROM=4.84 GB
「硬」设备型号=Custom Phone - 5.0.0 - API 21 - 768x1280
「硬」RAM=1.96 GB
/*Exception*/
java.lang.RuntimeException: 测试 
	at com.farbox.androidbyeleven.View.Activity.MainActivity.test(MainActivity.java:293)
	at com.farbox.androidbyeleven.View.Activity.MainActivity.onClick(MainActivity.java:286)
	at android.view.View.performClick(View.java:4756)
	at android.view.View$PerformClick.run(View.java:19749)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5221)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

```

**Comment by TomGarden** [comment]
123456789123456789

**Comment by TomGarden** [comment]
魑魅魍魉
