### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'io.github.TomGarden.tetris.CustomWeights.TomBeaker$TomBeakerStyle io.github.TomGarden.tetris.Fragments.GameFragment.getBeakerStyle()' on a null object reference

### ISSUE THREAD

**Issue by TomGarden-2** [TomGarden/Tetris#57]
```
/*Device Info*/
[硬]设备制造商=smartisan
[硬]设备型号=OD103
[硬]CPU型号= Qualcomm Technologies, Inc MSM8953Pro
[硬]RAM=3.52 GB
[硬]ROM=52.71 GB
[OS][三方定制系统版本]=Rock/odin/odin:7.1.1/NMF26F/1547630572:user/dev-keys
[OS]产品名称(adb shell)=odin
[OS][系统名称]=SMARTISAN
[OS][Android版本]=7.1.1(25)
[app]versionName=0.2.5-internal.2
[app]versionCode=5
/*Exception*/
java.lang.NullPointerException: Attempt to invoke virtual method 'io.github.TomGarden.tetris.CustomWeights.TomBeaker$TomBeakerStyle io.github.TomGarden.tetris.Fragments.GameFragment.getBeakerStyle()' on a null object reference
	at io.github.TomGarden.tetris.Activities.CustomThemeActivity.onOptionsItemSelected(CustomThemeActivity.java:148)
	at android.app.Activity.onMenuItemSelected(Activity.java:3332)
	at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:407)
	at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:195)
	at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:108)
	at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:108)
	at android.support.v7.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:63)
	at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:203)
	at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:780)
	at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:822)
	at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:171)
	at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:973)
	at android.support.v7.view.menu.MenuPopup.onItemClick(MenuPopup.java:127)
	at android.widget.AdapterView.performItemClick(AdapterView.java:310)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1274)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3297)
	at android.widget.AbsListView$5.run(AbsListView.java:4229)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:159)
	at android.app.ActivityThread.main(ActivityThread.java:6364)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1096)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:883)

```

**Comment by TomGarden-2** [comment]
```
/*Device Info*/
[硬]设备制造商=smartisan
[硬]设备型号=OD103
[硬]CPU型号= Qualcomm Technologies, Inc MSM8953Pro
[硬]RAM=3.52 GB
[硬]ROM=52.71 GB
[OS][三方定制系统版本]=Rock/odin/odin:7.1.1/NMF26F/1547630572:user/dev-keys
[OS]产品名称(adb shell)=odin
[OS][系统名称]=SMARTISAN
[OS][Android版本]=7.1.1(25)
[app]versionName=0.2.5-internal.2
[app]versionCode=5
/*Exception*/
java.lang.NullPointerException: Attempt to invoke virtual method 'io.github.TomGarden.tetris.CustomWeights.TomBeaker$TomBeakerStyle io.github.TomGarden.tetris.Fragments.GameFragment.getBeakerStyle()' on a null object reference
	at io.github.TomGarden.tetris.Activities.CustomThemeActivity.onOptionsItemSelected(CustomThemeActivity.java:148)
	at android.app.Activity.onMenuItemSelected(Activity.java:3332)
	at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:407)
	at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:195)
	at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:108)
	at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:108)
	at android.support.v7.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:63)
	at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:203)
	at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:780)
	at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:822)
	at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:171)
	at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:973)
	at android.support.v7.view.menu.MenuPopup.onItemClick(MenuPopup.java:127)
	at android.widget.AdapterView.performItemClick(AdapterView.java:310)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1274)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3297)
	at android.widget.AbsListView$5.run(AbsListView.java:4229)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:159)
	at android.app.ActivityThread.main(ActivityThread.java:6364)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1096)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:883)

```

**Comment by TomGarden-2** [comment]
```
/*Device Info*/
[硬]设备制造商=smartisan
[硬]设备型号=OD103
[硬]CPU型号= Qualcomm Technologies, Inc MSM8953Pro
[硬]RAM=3.52 GB
[硬]ROM=52.71 GB
[OS][三方定制系统版本]=Rock/odin/odin:7.1.1/NMF26F/1547630572:user/dev-keys
[OS]产品名称(adb shell)=odin
[OS][系统名称]=SMARTISAN
[OS][Android版本]=7.1.1(25)
[app]versionName=0.2.5-internal.2
[app]versionCode=5
/*Exception*/
java.lang.NullPointerException: Attempt to invoke virtual method 'io.github.TomGarden.tetris.CustomWeights.TomBeaker$TomBeakerStyle io.github.TomGarden.tetris.Fragments.GameFragment.getBeakerStyle()' on a null object reference
	at io.github.TomGarden.tetris.Activities.CustomThemeActivity.onOptionsItemSelected(CustomThemeActivity.java:148)
	at android.app.Activity.onMenuItemSelected(Activity.java:3332)
	at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:407)
	at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:195)
	at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:108)
	at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:108)
	at android.support.v7.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:63)
	at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:203)
	at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:780)
	at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:822)
	at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:171)
	at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:973)
	at android.support.v7.view.menu.MenuPopup.onItemClick(MenuPopup.java:127)
	at android.widget.AdapterView.performItemClick(AdapterView.java:310)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1274)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3297)
	at android.widget.AbsListView$5.run(AbsListView.java:4229)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:159)
	at android.app.ActivityThread.main(ActivityThread.java:6364)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1096)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:883)

```

**Comment by TomGarden-2** [comment]
```
/*Device Info*/
[硬]设备制造商=smartisan
[硬]设备型号=OD103
[硬]CPU型号= Qualcomm Technologies, Inc MSM8953Pro
[硬]RAM=3.52 GB
[硬]ROM=52.71 GB
[OS][三方定制系统版本]=Rock/odin/odin:7.1.1/NMF26F/1547630572:user/dev-keys
[OS]产品名称(adb shell)=odin
[OS][系统名称]=SMARTISAN
[OS][Android版本]=7.1.1(25)
[app]versionName=0.2.5-internal.2
[app]versionCode=5
/*Exception*/
java.lang.NullPointerException: Attempt to invoke virtual method 'io.github.TomGarden.tetris.CustomWeights.TomBeaker$TomBeakerStyle io.github.TomGarden.tetris.Fragments.GameFragment.getBeakerStyle()' on a null object reference
	at io.github.TomGarden.tetris.Activities.CustomThemeActivity.onOptionsItemSelected(CustomThemeActivity.java:148)
	at android.app.Activity.onMenuItemSelected(Activity.java:3332)
	at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:407)
	at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:195)
	at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:108)
	at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:108)
	at android.support.v7.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:63)
	at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:203)
	at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:780)
	at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:822)
	at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:171)
	at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:973)
	at android.support.v7.view.menu.MenuPopup.onItemClick(MenuPopup.java:127)
	at android.widget.AdapterView.performItemClick(AdapterView.java:310)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1274)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3297)
	at android.widget.AbsListView$5.run(AbsListView.java:4229)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:159)
	at android.app.ActivityThread.main(ActivityThread.java:6364)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1096)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:883)

```

**Comment by TomGarden-2** [comment]
```
/*Device Info*/
[硬]设备制造商=smartisan
[硬]设备型号=OD103
[硬]CPU型号= Qualcomm Technologies, Inc MSM8953Pro
[硬]RAM=3.52 GB
[硬]ROM=52.71 GB
[OS][三方定制系统版本]=Rock/odin/odin:7.1.1/NMF26F/1547630572:user/dev-keys
[OS]产品名称(adb shell)=odin
[OS][系统名称]=SMARTISAN
[OS][Android版本]=7.1.1(25)
[app]versionName=0.2.5-internal.2
[app]versionCode=5
/*Exception*/
java.lang.NullPointerException: Attempt to invoke virtual method 'io.github.TomGarden.tetris.CustomWeights.TomBeaker$TomBeakerStyle io.github.TomGarden.tetris.Fragments.GameFragment.getBeakerStyle()' on a null object reference
	at io.github.TomGarden.tetris.Activities.CustomThemeActivity.onOptionsItemSelected(CustomThemeActivity.java:148)
	at android.app.Activity.onMenuItemSelected(Activity.java:3332)
	at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:407)
	at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:195)
	at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:108)
	at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:108)
	at android.support.v7.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:63)
	at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:203)
	at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:780)
	at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:822)
	at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:171)
	at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:973)
	at android.support.v7.view.menu.MenuPopup.onItemClick(MenuPopup.java:127)
	at android.widget.AdapterView.performItemClick(AdapterView.java:310)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1274)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3297)
	at android.widget.AbsListView$5.run(AbsListView.java:4229)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:159)
	at android.app.ActivityThread.main(ActivityThread.java:6364)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1096)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:883)

```
