### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.os.Bundle.getInt(java.lang.String)' on a null object reference

### ISSUE THREAD

**Issue by TomGarden-2** [TomGarden/Tetris#7]
```
/*Device Info*/
[硬]设备制造商=Genymotion
[硬]设备型号=Custom
[硬]CPU型号=null
[硬]RAM=2.10 GB
[硬]ROM=13.38 GB
[OS][三方定制系统版本]=Android/vbox86p/vbox86p:8.0.0/OPR6.170623.017/32:userdebug/test-keys
[OS]产品名称(adb shell)=vbox86p
[OS][系统名称]=Android
[OS][Android版本]=8.0.0(26)
[app]versionName=1.0
[app]versionCode=1
/*Exception*/
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.os.Bundle.getInt(java.lang.String)' on a null object reference
	at com.farbox.androidbyeleven.View.Fragment.GameFragment.onCreateView(GameFragment.java:34)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java:2346)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1428)
	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
	at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
	at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
	at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
	at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2215)
	at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:649)
	at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:145)
	at android.support.v4.view.ViewPager.populate(ViewPager.java:1238)
	at android.support.v4.view.ViewPager.populate(ViewPager.java:1086)
	at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1616)
	at android.view.View.measure(View.java:21998)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:958)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
	at android.view.View.measure(View.java:21998)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6580)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at android.view.View.measure(View.java:21998)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6580)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
	at android.view.View.measure(View.java:21998)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6580)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:721)
	at android.view.View.measure(View.java:21998)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2410)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1498)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1751)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1386)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6733)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
	at android.view.Choreographer.doCallbacks(Choreographer.java:723)
	at android.view.Choreographer.doFrame(Choreographer.java:658)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

```

**Comment by TomGarden-2** [comment]
```
/*Device Info*/
[硬]设备制造商=Genymotion
[硬]设备型号=Custom
[硬]CPU型号=null
[硬]RAM=2.10 GB
[硬]ROM=13.38 GB
[OS][三方定制系统版本]=Android/vbox86p/vbox86p:8.0.0/OPR6.170623.017/32:userdebug/test-keys
[OS]产品名称(adb shell)=vbox86p
[OS][系统名称]=Android
[OS][Android版本]=8.0.0(26)
[app]versionName=1.0
[app]versionCode=1
/*Exception*/
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.os.Bundle.getInt(java.lang.String)' on a null object reference
	at com.farbox.androidbyeleven.View.Fragment.GameFragment.onCreateView(GameFragment.java:34)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java:2346)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1428)
	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
	at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
	at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
	at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
	at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2215)
	at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:649)
	at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:145)
	at android.support.v4.view.ViewPager.populate(ViewPager.java:1238)
	at android.support.v4.view.ViewPager.populate(ViewPager.java:1086)
	at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1616)
	at android.view.View.measure(View.java:21998)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:958)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
	at android.view.View.measure(View.java:21998)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6580)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at android.view.View.measure(View.java:21998)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6580)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
	at android.view.View.measure(View.java:21998)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6580)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:721)
	at android.view.View.measure(View.java:21998)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2410)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1498)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1751)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1386)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6733)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
	at android.view.Choreographer.doCallbacks(Choreographer.java:723)
	at android.view.Choreographer.doFrame(Choreographer.java:658)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

```

**Comment by TomGarden-2** [comment]
```
/*Device Info*/
[硬]设备制造商=Genymotion
[硬]设备型号=Custom
[硬]CPU型号=null
[硬]RAM=2.10 GB
[硬]ROM=13.38 GB
[OS][三方定制系统版本]=Android/vbox86p/vbox86p:8.0.0/OPR6.170623.017/32:userdebug/test-keys
[OS]产品名称(adb shell)=vbox86p
[OS][系统名称]=Android
[OS][Android版本]=8.0.0(26)
[app]versionName=1.0
[app]versionCode=1
/*Exception*/
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.os.Bundle.getInt(java.lang.String)' on a null object reference
	at com.farbox.androidbyeleven.View.Fragment.GameFragment.onCreateView(GameFragment.java:34)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java:2346)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1428)
	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
	at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
	at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
	at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
	at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2215)
	at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:649)
	at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:145)
	at android.support.v4.view.ViewPager.populate(ViewPager.java:1238)
	at android.support.v4.view.ViewPager.populate(ViewPager.java:1086)
	at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1616)
	at android.view.View.measure(View.java:21998)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:958)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
	at android.view.View.measure(View.java:21998)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6580)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at android.view.View.measure(View.java:21998)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6580)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
	at android.view.View.measure(View.java:21998)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6580)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:721)
	at android.view.View.measure(View.java:21998)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2410)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1498)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1751)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1386)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6733)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
	at android.view.Choreographer.doCallbacks(Choreographer.java:723)
	at android.view.Choreographer.doFrame(Choreographer.java:658)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

```

**Comment by TomGarden-2** [comment]
```
/*Device Info*/
[硬]设备制造商=Genymotion
[硬]设备型号=Custom
[硬]CPU型号=null
[硬]RAM=1.04 GB
[硬]ROM=13.38 GB
[OS][三方定制系统版本]=Android/vbox86p/vbox86p:8.0.0/OPR6.170623.017/32:userdebug/test-keys
[OS]产品名称(adb shell)=vbox86p
[OS][系统名称]=Android
[OS][Android版本]=8.0.0(26)
[app]versionName=1.0
[app]versionCode=1
/*Exception*/
java.lang.RuntimeException: (TomGestureDetector.java:241)>>>case = 7
	at io.github.TomGarden.tom_log.LogUtil.ASSERT(LogUtil.java:244)
	at io.github.TomGarden.tetris.Control.TomGestureDetector.onSingleTapUpLevel_1_3(TomGestureDetector.java:241)
	at io.github.TomGarden.tetris.Control.TomGestureDetector.onSingleTapUp(TomGestureDetector.java:203)
	at android.view.GestureDetector.onTouchEvent(GestureDetector.java:640)
	at io.github.TomGarden.tetris.Control.TomGestureDetector$GestureDetector.onTouchEvent(TomGestureDetector.java:84)
	at io.github.TomGarden.tetris.Control.TomGestureDetector.onTouchEvent(TomGestureDetector.java:178)
	at io.github.TomGarden.tetris.CustomWeights.TomConstraintLayout.onTouchEvent(TomConstraintLayout.java:46)
	at android.view.View.dispatchTouchEvent(View.java:11721)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2955)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2636)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2961)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2961)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2961)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2961)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2961)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2961)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:445)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1828)
	at android.app.Activity.dispatchTouchEvent(Activity.java:3292)
	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:407)
	at android.view.View.dispatchPointerEvent(View.java:11960)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4776)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4590)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4128)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4181)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4147)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4274)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4155)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4331)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4128)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4181)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4147)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4155)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4128)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6642)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6616)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6577)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6745)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:325)
	at android.os.Looper.loop(Looper.java:142)
	at android.app.ActivityThread.main(ActivityThread.java:6541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

```
