### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke interface method 'void com.farbox.androidbyeleven.Controller.V2M.IBeakerConditionService.setBeakerSize(int, int)' on a null object reference

### ISSUE THREAD

**Issue by TomGarden-2** [TomGarden/Tetris#8]
```
/*Device Info*/
[硬]设备制造商=Genymotion
[硬]设备型号=Custom
[硬]CPU型号=null
[硬]RAM=2.10 GB
[硬]ROM=13.38 GB
[OS][三方定制系统版本]=Android/vbox86p/vbox86p:8.0.0/OPR6.170623.017/32:userdebug/test-keys
[OS]产品名称(adb shell)=vbox86p
[OS][系统名称]=Android
[OS][Android版本]=8.0.0(26)
[app]versionName=1.0
[app]versionCode=1
/*Exception*/
java.lang.NullPointerException: Attempt to invoke interface method 'void com.farbox.androidbyeleven.Controller.V2M.IBeakerConditionService.setBeakerSize(int, int)' on a null object reference
	at com.farbox.androidbyeleven.View.Weight.Beaker.onMeasure(Beaker.java:89)
	at android.view.View.measure(View.java:21998)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6580)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at android.view.View.measure(View.java:21998)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6580)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
	at android.widget.TableRow.measureChildBeforeLayout(TableRow.java:246)
	at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1167)
	at android.widget.TableRow.onMeasure(TableRow.java:113)
	at android.view.View.measure(View.java:21998)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6580)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
	at android.view.View.measure(View.java:21998)
	at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1632)
	at android.view.View.measure(View.java:21998)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:958)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
	at android.view.View.measure(View.java:21998)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6580)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at android.view.View.measure(View.java:21998)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6580)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
	at android.view.View.measure(View.java:21998)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6580)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:721)
	at android.view.View.measure(View.java:21998)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2410)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1498)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1751)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1386)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6733)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
	at android.view.Choreographer.doCallbacks(Choreographer.java:723)
	at android.view.Choreographer.doFrame(Choreographer.java:658)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

```

**Comment by TomGarden-2** [comment]
```
/*Device Info*/
[硬]设备制造商=Genymotion
[硬]设备型号=Custom
[硬]CPU型号=null
[硬]RAM=2.10 GB
[硬]ROM=13.38 GB
[OS][三方定制系统版本]=Android/vbox86p/vbox86p:8.0.0/OPR6.170623.017/32:userdebug/test-keys
[OS]产品名称(adb shell)=vbox86p
[OS][系统名称]=Android
[OS][Android版本]=8.0.0(26)
[app]versionName=1.0
[app]versionCode=1
/*Exception*/
java.lang.NullPointerException: Attempt to invoke interface method 'void com.farbox.androidbyeleven.Controller.V2M.IBeakerConditionService.setBeakerSize(int, int)' on a null object reference
	at com.farbox.androidbyeleven.View.Weight.Beaker.onMeasure(Beaker.java:89)
	at android.view.View.measure(View.java:21998)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6580)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at android.view.View.measure(View.java:21998)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6580)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
	at android.widget.TableRow.measureChildBeforeLayout(TableRow.java:246)
	at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1167)
	at android.widget.TableRow.onMeasure(TableRow.java:113)
	at android.view.View.measure(View.java:21998)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6580)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
	at android.view.View.measure(View.java:21998)
	at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1632)
	at android.view.View.measure(View.java:21998)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:958)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
	at android.view.View.measure(View.java:21998)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6580)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at android.view.View.measure(View.java:21998)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6580)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
	at android.view.View.measure(View.java:21998)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6580)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:721)
	at android.view.View.measure(View.java:21998)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2410)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1498)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1751)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1386)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6733)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
	at android.view.Choreographer.doCallbacks(Choreographer.java:723)
	at android.view.Choreographer.doFrame(Choreographer.java:658)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

```

**Comment by TomGarden-2** [comment]
```
/*Device Info*/
[硬]设备制造商=Genymotion
[硬]设备型号=Custom
[硬]CPU型号=null
[硬]RAM=2.10 GB
[硬]ROM=13.38 GB
[OS][三方定制系统版本]=Android/vbox86p/vbox86p:8.0.0/OPR6.170623.017/32:userdebug/test-keys
[OS]产品名称(adb shell)=vbox86p
[OS][系统名称]=Android
[OS][Android版本]=8.0.0(26)
[app]versionName=1.0
[app]versionCode=1
/*Exception*/
java.lang.NullPointerException: Attempt to invoke interface method 'void com.farbox.androidbyeleven.Controller.V2M.IBeakerConditionService.setBeakerSize(int, int)' on a null object reference
	at com.farbox.androidbyeleven.View.Weight.Beaker.onMeasure(Beaker.java:89)
	at android.view.View.measure(View.java:21998)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6580)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at android.view.View.measure(View.java:21998)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6580)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
	at android.widget.TableRow.measureChildBeforeLayout(TableRow.java:246)
	at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1167)
	at android.widget.TableRow.onMeasure(TableRow.java:113)
	at android.view.View.measure(View.java:21998)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6580)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
	at android.view.View.measure(View.java:21998)
	at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1632)
	at android.view.View.measure(View.java:21998)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:958)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
	at android.view.View.measure(View.java:21998)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6580)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at android.view.View.measure(View.java:21998)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6580)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
	at android.view.View.measure(View.java:21998)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6580)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:721)
	at android.view.View.measure(View.java:21998)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2410)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1498)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1751)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1386)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6733)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
	at android.view.Choreographer.doCallbacks(Choreographer.java:723)
	at android.view.Choreographer.doFrame(Choreographer.java:658)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

```
